language: ruby
rvm:
  - 2.2
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile
script: "bundle exec rake coverage"
before_install:
  - gem install bundler

bundler_args: --retry 5
cache: bundler
